### ISSUE TITLE
Issue when using the ppo with Cartpole

### ISSUE THREAD

**Issue by EliottEccidio** [vwxyzjn/ppo-implementation-details#4]
Hi sorry to bother you, 

I was trying to run the the code from your wideo with Weights & Biases but I have errors when I want to run it. First of all there isn't a seed attribute for the env. To replace env.seed(seed) I have used :
```python
env.reset(seed=seed)
```
Now I have an issue with:
```python
next_obs = torch.Tensor(envs.reset()).to(device)
# Returns the error:
ValueError: expected sequence of length 4 at dim 1 (got 0)
```
 To try and resolve it I print the tupple and converted it into an array before converting it into a Tensor :
```python
env_reset_ar = np.asarray(envs.reset(), dtype=tuple)
next_obs = torch.Tensor(env_reset_ar).to(device) # store the initial obs 
#With env.reset() : 

#[[-0.01702683  0.02884287 -0.01968052 -0.00465021]
# [-0.00673692  0.01692973 -0.00772153  0.01331844]
# [-0.0069372   0.00867986  0.02378378  0.04562673]
# [-0.00695037  0.02889467  0.0484153  -0.01302742]]
#{} 

# But Now I have the  Error :
next_obs = torch.Tensor(env_reset_ar).to(device) # store the initial obs 
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.
```
Do you know what do I need to change to make it work ? I am still a beginner at RL so I don't know what have I done wrong.  
Thank you in advance.

Kind regards,
Eliott.

**Comment by Maxxxel** [comment]
Heads up for others:
`
envs.reset()[0]
`
Also another fix:
`
next_obs, reward, done, info = envs.step(action.cpu().numpy())
`
Should be
`
next_obs, reward, terminated, truncated, info = envs.step(action.cpu().numpy())
done = terminated | truncated
`
And
`
for item in info:
    if "episode" in item.keys():
`
to
`
if len(info) > 0:
    for env_info in info:
        if env_info is not None and env_info == "final_info":
            for item in info["final_info"]:
                if item is not None:
                    if "episode" in item.keys():
                        print(f"global_step={global_step}, episodic_return={item['episode']['r']}")
                        writer.add_scalar("charts/episodic_return", item["episode"]["r"], global_step)
                        writer.add_scalar("charts/episodic_length", item["episode"]["l"], global_step)
                        break
`
also change first line
`import gym`
to
`ìmport gymnasium as gym`

**Comment by thivyanth** [comment]
`next_obs = torch.Tensor(envs.reset()[0]).to(device)`
has worked for me
